version: '2'
services:
  web:
    build: .
    ports:
      - '8080:3000'
      - '80:80'
    environment:
      SECRET_KEY_BASE: yourkeyhere
      POSTGRES_USER: euthymia
      MAIL_USER: euthymia.notifier@gmail.com
    env_file:
      - ./euthymia.env
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_USER: euthymia
